package dao_tests.interfaces;

import domain.Role;
import java.util.List;

public interface IRoleDao {

    /**
     * Find all persisted roles
     * @return a list of roles
     */
    List<Role> findAll();

    /**
     * Find one persisted role by a unique id
     * @param id of the role
     * @return a role
     */
    Role findById(Long id);

    /**
     * Find one persisted role by a unique name
     * @param name of the role
     * @return a role
     */
    Role findByName(String name);

    /**
     * Persists a new role
     * A unique id will be generated by the persistency framework
     * @param role to be persisted
     * @return a persisted role
     */
    Role create(Role role);

    /**
     * Persists a list of new roles
     * A unique id will be generated by the persistency framework
     * @param roles to be persisted
     * @return a list of persisted roles
     */
    List<Role> create(List<Role> roles);

    /**
     * Updates an persisted role
     * If the role already exists, the role gets persisted
     * @param role to be updated
     * @return an updated role
     */
    Role update(Role role);

    /**
     * Removes one persisted role
     * If the role doesn't exist, a false will return
     * @param role to be removed
     * @return true (if successful) or false
     */
    boolean remove(Role role);
}
