package DaoInterfaces;

import Domain.Hashtag;
import java.util.List;

public interface IHashtagDao {

    /**
     * Find all persisted hashtags
     * @return a list of hastags
     */
    List<Hashtag> findAll();

    /**
     * Find one persisted hashtag by a unique id
     * @param id of the hashtag
     * @return a hashtag
     */
    Hashtag findById(Long id);

    /**
     * Find one persisted hashtag by a unique name
     * @param name of the hashtag (comes after '#')
     * @return a hashtag
     */
    Hashtag findByName(String name);

    /**
     * Persists a new hashtgag
     * A unique id will be generated by the persistency framework
     * @param hashtag to be persisted
     * @return a persisted hashtag
     */
    Hashtag create(Hashtag hashtag);

    /**
     * Persists a list of new hashtags
     * A unique id will be generated by the persistency framework
     * @param hashtags to be persisted
     * @return a list of persisted hashtags
     */
    List<Hashtag> create(List<Hashtag> hashtags);

    /**
     * Updates an persisted hashtag
     * If the hashtag already exists, the hashtag gets persisted
     * @param hashtag to be updated
     * @return an updated hashtag
     */
    Hashtag update(Hashtag hashtag);

    /**
     * Removes one persisted hashtag
     * If the hashtag doesn't exist, a false will return
     * @param hashtag to be removed
     * @return true (if successful) or false
     */
    boolean remove(Hashtag hashtag);
}
